//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddleLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long AccountID { get; set; }
        public string CompanyName { get; set; }
        public string AddLine1 { get; set; }
        public string AddLine2 { get; set; }
        public string AddLine3 { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public string TinNo { get; set; }
        public string WebSite { get; set; }
        public Nullable<bool> IsSupplier { get; set; }
        public Nullable<bool> IsManufacturer { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
    }
}
