//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddleLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<decimal> PRate { get; set; }
        public Nullable<decimal> MarginPer { get; set; }
        public Nullable<decimal> MarginAmount { get; set; }
        public Nullable<decimal> SRate { get; set; }
        public Nullable<decimal> InitStock { get; set; }
        public Nullable<int> MagUnitID { get; set; }
    }
}
