//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddleLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public long SaleID { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string SaleNo { get; set; }
        public string CustomerID { get; set; }
        public string PaymentMethodID { get; set; }
        public string PaymentRefrenceID { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> DiscountPer { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string Remarks { get; set; }
    }
}
