//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddleLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeDetail
    {
        public int TypeId { get; set; }
        public Nullable<int> TypeCode { get; set; }
        public string TypeName { get; set; }
        public string DetailName { get; set; }
    }
}
